language: cpp
compiler: 
    - gcc
notifications:
    email: false
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/julianightlies -y
    - sudo apt-get update -qq -y
    - sudo apt-get upgrade -y
    - sudo apt-get install julia gsl-bin -y
    - git config --global user.name "Dummy Travis User"
    - git config --global user.email "travis@example.net"
script:
    - julia -e 'versioninfo(); Pkg.init();'
    - mkdir -p ~/.julia/GSL
    - cp -R ./* ~/.julia/GSL/
    - for a in ~/.julia/GSL/test/*.jl; do julia $a; errcode=$?; if test $errcode -ne 0; then exit $errcode; fi; done
    
