language: cpp
compiler: 
    - clang
notifications:
    email: false
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/julianightlies -y
    - sudo apt-get update -qq -y
    - sudo apt-get install libpcre3-dev julia -y
    - git config --global user.name "Dummy Travis User"
    - git config --global user.email "travis@example.net"
script:
    - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("GSL"))`); Pkg.pin("GSL"); Pkg.resolve()'
    - julia -e 'Pkg.build(); using GSL; @assert isdefined(:GSL); @assert typeof(GSL) === Module'
    - cd ~/.julia/GSL/test; julia test.jl

